import AppKit
import Testing
@testable import Nook

/// The clipboard under test is a named one, never `.general`: a test must not
/// touch what the person running it has copied.
@MainActor
@Suite("The booking name on the clipboard")
struct BookingClipboardTests {

    /// A type declared on an item whose provider hands back nothing — the
    /// shape of a promise an app that has quit will not fulfil.
    private static let missingType = NSPasteboard.PasteboardType("com.khabirov.nook.tests.missing")

    private func pasteboard(_ label: String) -> NSPasteboard {
        let board = NSPasteboard(name: .init("com.khabirov.nook.tests.\(label)"))
        board.clearContents()
        return board
    }

    /// One line per slot: Sheets reads a paste as TSV, so the name spreads
    /// down the rows of the booking instead of landing in one cell.
    @Test("A name per slot, one line each")
    func linePerSlot() {
        #expect(BookingClipboard.text("Ana Petrović", slots: 1) == "Ana Petrović")
        #expect(BookingClipboard.text("Ana Petrović", slots: 3) ==
            "Ana Petrović\nAna Petrović\nAna Petrović")
        // A malformed duration must not produce an empty paste.
        #expect(BookingClipboard.text("Ana Petrović", slots: 0) == "Ana Petrović")
    }

    @Test("Formula prefixes are pasted as literal cell text", arguments: ["=Ana", "+Ana", "-Ana", "@Ana"])
    func formulaPrefixes(name: String) {
        #expect(BookingClipboard.text(name, slots: 2) == "'\(name)\n'\(name)")
    }

    @Test("Booking names cannot contain TSV separators")
    func normalizesSeparators() {
        #expect(Preferences.normalizedBookingName(" Ana\tPetrović\nHQ ") == "Ana Petrović HQ")
        #expect(Preferences.normalizedBookingName(" \n\t ") == nil)
        #expect(Preferences.replacingBookingSeparators(in: "Ana ") == "Ana ")
    }

    @Test("The name is asked not to be kept in clipboard history")
    func carriesTheMarkers() throws {
        let board = pasteboard("markers")
        #expect(BookingClipboard(pasteboard: board).place("Ana Petrović", slots: 2, hold: nil))

        let item = try #require(board.pasteboardItems?.first)
        #expect(item.string(forType: .string) == "Ana Petrović\nAna Petrović")
        for marker in ["ConcealedType", "TransientType", "AutoGeneratedType"] {
            #expect(item.types.contains(.init("org.nspasteboard.\(marker)")),
                    "missing org.nspasteboard.\(marker)")
        }
    }

    @Test("What the person had comes back")
    func restoresThePrevious() {
        let board = pasteboard("restore")
        board.setString("something of their own", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 2, hold: nil))
        #expect(board.string(forType: .string) == "Ana Petrović\nAna Petrović")

        clipboard.restoreIfUntouched()
        #expect(board.string(forType: .string) == "something of their own")
    }

    /// A clipboard that cannot be put back exactly is not touched at all.
    ///
    /// One item carries the same content in several representations, and some
    /// are promises a quit app will not fulfil. Keeping the readable ones and
    /// dropping the rest would be guessing which one the next application
    /// wants — so the copy is refused instead, and the overlay says so rather
    /// than sending anybody to the sheet with the old clipboard loaded.
    @Test("An item that cannot be copied whole leaves the clipboard alone")
    func refusesWhatCannotBePutBack() throws {
        let board = pasteboard("partial")
        let item = NSPasteboardItem()
        item.setString("something of their own", forType: .string)
        item.setDataProvider(MissingPasteboardData(), forTypes: [Self.missingType])
        board.writeObjects([item])
        // Pins the double, so the test cannot pass by the type being absent:
        // it is declared on the item and it does hand back nothing.
        let written = try #require(board.pasteboardItems?.first)
        #expect(written.types.contains(Self.missingType))
        #expect(written.data(forType: Self.missingType) == nil)
        let before = board.changeCount

        let placed = BookingClipboard(pasteboard: board).place("Ana Petrović", slots: 1, hold: nil)

        #expect(!placed)
        #expect(board.changeCount == before)
        #expect(board.string(forType: .string) == "something of their own")
    }

    /// The refusal must not depend on the name being the interesting part: an
    /// item with nothing readable at all is refused the same way.
    @Test("Nothing readable at all is refused too")
    func refusesAnUnreadableItem() {
        let board = pasteboard("unreadable")
        let unavailable = NSPasteboardItem()
        unavailable.setDataProvider(MissingPasteboardData(), forTypes: [Self.missingType])
        board.writeObjects([unavailable])
        let before = board.changeCount

        let placed = BookingClipboard(pasteboard: board).place("Ana Petrović", slots: 1, hold: nil)

        #expect(!placed)
        #expect(board.changeCount == before)
    }

    /// The one thing the change count is good for: it cannot see a paste, but
    /// it can see that somebody copied after us — and then the snapshot is
    /// stale and must not go back on.
    @Test("A copy made after us is not overwritten")
    func leavesANewerCopyAlone() {
        let board = pasteboard("newer")
        board.setString("older", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: nil))
        board.clearContents()
        board.setString("copied by the person", forType: .string)

        clipboard.restoreIfUntouched()
        #expect(board.string(forType: .string) == "copied by the person")
    }

    /// Two bookings in a row: the second must still give back the person’s own
    /// clipboard, not the first booking’s name.
    @Test("A second booking does not snapshot the first one")
    func doesNotSnapshotItself() {
        let board = pasteboard("twice")
        board.setString("something of their own", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: nil))
        #expect(clipboard.place("Ana Petrović", slots: 4, hold: nil))

        clipboard.restoreIfUntouched()
        #expect(board.string(forType: .string) == "something of their own")
    }

    @Test("The hold expires and the clipboard comes back on its own")
    func restoresAfterTheHold() async throws {
        let board = pasteboard("hold")
        board.setString("something of their own", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: .milliseconds(50)))
        #expect(board.string(forType: .string) == "Ana Petrović")

        try await Task.sleep(for: .milliseconds(400))
        #expect(board.string(forType: .string) == "something of their own")
    }

    /// An empty clipboard is a state worth putting back, not an absence of
    /// one: a fresh login where nobody has copied anything yet. Treated as
    /// “nothing to restore”, the name would sit there for good while the
    /// setting promised a limited hold.
    @Test("An empty clipboard is given back as empty")
    func restoresAnEmptyClipboard() async throws {
        let board = pasteboard("empty")
        #expect(board.pasteboardItems?.isEmpty == true)

        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: .milliseconds(50)))
        #expect(board.string(forType: .string) == "Ana Petrović")

        try await Task.sleep(for: .milliseconds(400))
        #expect(board.string(forType: .string) == nil)
        #expect(board.pasteboardItems?.isEmpty == true)
    }

    /// The safe end of the setting: nothing can overtake the paste, because
    /// nothing is scheduled at all.
    @Test("Without a hold the name simply stays")
    func staysWithoutAHold() async throws {
        let board = pasteboard("no-hold")
        board.setString("something of their own", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: nil))

        try await Task.sleep(for: .milliseconds(200))
        #expect(board.string(forType: .string) == "Ana Petrović")
    }

    @Test("A pending hold restores before termination")
    func restoresBeforeTermination() {
        let board = pasteboard("termination")
        board.setString("something of their own", forType: .string)
        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: .seconds(60)))

        clipboard.restoreBeforeTermination()

        #expect(board.string(forType: .string) == "something of their own")
    }

    @Test("The never-restore mode stays on the clipboard at termination")
    func neverRestoreSurvivesTermination() {
        let board = pasteboard("termination-no-hold")
        board.setString("something of their own", forType: .string)
        let clipboard = BookingClipboard(pasteboard: board)
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: nil))

        clipboard.restoreBeforeTermination()

        #expect(board.string(forType: .string) == "Ana Petrović")
    }

    @Test("Switching to never restore disarms a pending restoration")
    func switchingToNeverRestoreDisarmsThePendingRestoration() {
        let board = pasteboard("timer-to-no-hold")
        board.setString("something of their own", forType: .string)
        let clipboard = BookingClipboard(pasteboard: board, frontmostBundleID: { Self.safari })
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: .seconds(60), openedIn: Self.safari))

        #expect(clipboard.place("Miloš Jovanović", slots: 1, hold: nil, openedIn: Self.safari))
        clipboard.noteActivation(of: "com.apple.dt.Xcode")
        clipboard.restoreBeforeTermination()

        #expect(board.string(forType: .string) == "Miloš Jovanović")
    }

    /// Leaving the application the sheet opened in is the end of the booking —
    /// the earliest honest moment to hand the clipboard back, and the one that
    /// keeps the name out of the next application’s ⌘V.
    ///
    /// The order is what makes this delicate: the browser comes to the front
    /// **after** the name is copied, so its own arrival must not be read as
    /// leaving — that would take the name away before it could be pasted.
    @Test("An activation means nothing until the sheet has been to the front")
    func readsActivations() {
        let safari = Self.safari
        // The browser arriving is not leaving, however it is read.
        #expect(BookingClipboard.activation(of: safari, sheetApp: safari, sawSheetApp: false)
            == .arrivedAtSheet)
        #expect(BookingClipboard.activation(of: safari, sheetApp: safari, sawSheetApp: true)
            == .arrivedAtSheet)
        // Something else before the browser ever showed up: the link may still
        // be opening, and the name has to survive until it does.
        #expect(BookingClipboard.activation(of: "com.apple.dt.Xcode", sheetApp: safari, sawSheetApp: false)
            == .irrelevant)
        // The same switch once the sheet has been in front — that is leaving.
        #expect(BookingClipboard.activation(of: "com.apple.dt.Xcode", sheetApp: safari, sawSheetApp: true)
            == .leftTheSheet)
        // An unidentifiable application counts as leaving all the same.
        #expect(BookingClipboard.activation(of: nil, sheetApp: safari, sawSheetApp: true)
            == .leftTheSheet)
        // Nothing was opened, so there is nothing to leave.
        #expect(BookingClipboard.activation(of: safari, sheetApp: nil, sawSheetApp: true)
            == .irrelevant)
    }

    /// The regression that mattered: the overlay is a non-activating panel, so
    /// ⌥Space over a browser leaves that browser frontmost, and opening a tab
    /// in an already-frontmost application posts no activation. Seeded at
    /// `false`, the browser would never count as visited and leaving would
    /// never hand the clipboard back — in the commonest way of booking there
    /// is.
    @Test("Leaving works when the sheet’s application was already in front")
    func restoresWhenTheBrowserWasAlreadyFrontmost() {
        let board = pasteboard("already-front")
        board.setString("something of their own", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board, frontmostBundleID: { Self.safari })
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: .seconds(60), openedIn: Self.safari))
        #expect(board.string(forType: .string) == "Ana Petrović")

        clipboard.noteActivation(of: "com.apple.dt.Xcode")
        #expect(board.string(forType: .string) == "something of their own")
    }

    /// And the other way round: booking from some other application, the
    /// browser has to arrive before leaving it can mean anything — otherwise
    /// its own arrival would take the name away before ⌘V.
    @Test("Leaving counts only after the sheet’s application has arrived")
    func waitsForTheBrowserWhenBookingElsewhere() {
        let board = pasteboard("arrives-later")
        board.setString("something of their own", forType: .string)

        let clipboard = BookingClipboard(pasteboard: board,
                                         frontmostBundleID: { "com.apple.dt.Xcode" })
        #expect(clipboard.place("Ana Petrović", slots: 1, hold: .seconds(60), openedIn: Self.safari))

        // Some other application in the meantime: the link may still be
        // opening, so the name must survive.
        clipboard.noteActivation(of: "com.apple.finder")
        #expect(board.string(forType: .string) == "Ana Petrović")

        clipboard.noteActivation(of: Self.safari)
        #expect(board.string(forType: .string) == "Ana Petrović")

        clipboard.noteActivation(of: "com.apple.dt.Xcode")
        #expect(board.string(forType: .string) == "something of their own")
    }

    private static let safari = "com.apple.Safari"

    /// Every value the settings window offers is either a duration or the
    /// “until something else is copied” entry — and 15 seconds, the default,
    /// has to be among them or the list would open on nothing.
    @Test("The list of durations is well formed")
    func presetsAreWellFormed() {
        #expect(BookingClipboard.holdPresets.allSatisfy { $0 >= 0 })
        #expect(BookingClipboard.holdPresets.contains(BookingClipboard.defaultHoldSeconds))
        #expect(BookingClipboard.holdPresets.contains(0))
        #expect(Set(BookingClipboard.holdPresets).count == BookingClipboard.holdPresets.count)
    }
}

private final class MissingPasteboardData: NSObject, NSPasteboardItemDataProvider {
    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {}
}
