import AppKit

/// The booking name, put on the clipboard so that one ⌘V fills the cells the
/// sheet opened on, and taken back off it afterwards.
///
/// Why the clipboard at all: a deep link can select cells but cannot put
/// anything in them — the fragment carries `gid` and `range`, and nothing
/// else. Until the app writes to the sheet itself, the clipboard is the only
/// way the name can travel without a credential.
@MainActor
final class BookingClipboard {
    /// How long the name stays before the person’s own clipboard comes back.
    ///
    /// A bet on the warm case: the sheet is already loaded in a tab, the caret
    /// lands on the cells at once, and ⌘V follows within a few seconds. A cold
    /// load of the whole workbook takes longer than this, and then the restore
    /// wins the race — the paste puts whatever was on the clipboard before
    /// into the booking grid. That is the cost of the number, and the reason
    /// the setting exists at all.
    ///
    /// **A paste cannot be detected.** `NSPasteboard` reports writes, never
    /// reads, so “pasted” and “walked away” look the same from here. Every
    /// scheme — a timer, the browser losing focus — is therefore a guess; a
    /// tab switch, the commonest ending of all, is invisible to all of them.
    /// Hence a duration a person can raise rather than a cleverer trigger.
    static let defaultHoldSeconds = 15

    /// What the settings window offers. `0` is “until something else is
    /// copied”: no restore at all, the safe end of the scale — nothing can
    /// then overtake the paste.
    ///
    /// A list rather than a number field: a figure typed by hand can be too
    /// small, and too small means a paste of the previous clipboard into a
    /// sheet the whole coworking shares.
    static let holdPresets = [15, 30, 45, 60, 180, 300, 600, 1200, 0]

    /// Markers from the `nspasteboard.org` convention. Clipboard managers that
    /// honour them keep this item out of their history — and it is the name of
    /// a living person, not a scrap of text. A convention, not an Apple
    /// guarantee: a manager that has not heard of it will store the name.
    private static let markers: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard: NSPasteboard
    /// Who is in front at the moment a booking is opened. Injected so the
    /// seeding of `sawSheetApp` is under test: it is the part that decides
    /// whether leaving works at all.
    private let frontmostBundleID: () -> String?
    private var saved: [NSPasteboardItem]?
    /// The change count our own write left behind. Anything else means
    /// somebody has copied since, and the snapshot must not go back on.
    private var stamp: Int?
    private var restore: Task<Void, Never>?
    /// The application the sheet was opened in, and whether it has been to the
    /// front yet. Leaving it is the end of the booking, and the earliest
    /// moment the name is no longer wanted.
    private var sheetApp: String?
    private var sawSheetApp = false
    private var watch: NSObjectProtocol?

    init(
        pasteboard: NSPasteboard = .general,
        frontmostBundleID: @escaping () -> String? = {
            NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        }
    ) {
        self.pasteboard = pasteboard
        self.frontmostBundleID = frontmostBundleID
    }

    /// What an application coming to the front means for the name.
    ///
    /// Pure, so the reasoning is under test while the notification plumbing
    /// stays three lines. The order matters: the sheet’s own application comes
    /// to the front **after** the name is copied, and reading that as leaving
    /// would take the name away before ⌘V.
    enum Activation: Equatable {
        /// The sheet is now in front; from here on, leaving means something.
        case arrivedAtSheet
        /// The person has gone somewhere else — the booking is over.
        case leftTheSheet
        case irrelevant
    }

    static func activation(of bundleID: String?, sheetApp: String?, sawSheetApp: Bool) -> Activation {
        guard let sheetApp else { return .irrelevant }
        if bundleID == sheetApp { return .arrivedAtSheet }
        return sawSheetApp ? .leftTheSheet : .irrelevant
    }

    /// One line per slot: Sheets reads a paste as TSV, so newlines spread the
    /// name down the rows of the booking. A quarter of an hour is one line.
    static func text(_ name: String, slots: Int) -> String {
        let literal = literalCell(name)
        return Array(repeating: literal, count: max(1, slots)).joined(separator: "\n")
    }

    /// Google Sheets treats these prefixes as formulas when plain text is
    /// pasted. A leading apostrophe asks it to store the following value as
    /// literal text; the apostrophe itself is not displayed in the cell.
    private static func literalCell(_ name: String) -> String {
        guard let first = name.first, "=+-@".contains(first) else { return name }
        return "'\(name)"
    }

    /// `hold` is read per booking rather than held by this object, so a change
    /// in the settings window takes effect on the next ⏎ rather than on the
    /// next launch. `nil` leaves the name on the clipboard until something
    /// else is copied, and then nothing is watched either: that setting is a
    /// person asking for the name to stay.
    ///
    /// `openedIn` is the application the sheet is about to open in. Leaving it
    /// puts the clipboard back at once, which is the earliest honest end of
    /// the booking — otherwise the name sits there for the whole hold and
    /// ⌘V in the next application pastes it. The hold still covers what this
    /// cannot see: a switch to another tab, or a tab closed without leaving
    /// the browser.
    ///
    /// `false` — the clipboard was left exactly as it was and nothing was
    /// copied. **The result has to be acted on**: the overlay promises the
    /// copy before ⏎ is pressed, and a caller that ignored a refusal would
    /// send the person to a sheet with four cells selected and their old
    /// clipboard still loaded, ready for ⌘V to put it in.
    func place(_ name: String, slots: Int, hold: Duration?, openedIn bundleID: String? = nil) -> Bool {
        // Our own write is not “what the person had”: without this, a second
        // booking would snapshot the first booking’s name as the thing to
        // give back.
        if stamp != pasteboard.changeCount {
            guard let snapshot = Self.snapshot(pasteboard) else { return false }
            saved = snapshot
        }
        restore?.cancel()
        restore = nil

        let item = NSPasteboardItem()
        item.setString(Self.text(name, slots: slots), forType: .string)
        for marker in Self.markers {
            item.setData(Data(), forType: marker)
        }
        pasteboard.clearContents()
        // `clearContents` has already emptied it, so a failed write leaves the
        // person with nothing at all. Put the snapshot straight back.
        guard pasteboard.writeObjects([item]) else {
            if let saved, !saved.isEmpty {
                pasteboard.clearContents()
                pasteboard.writeObjects(saved)
            }
            saved = nil
            stamp = nil
            stopWatching()
            return false
        }
        stamp = pasteboard.changeCount

        guard let hold else {
            stopWatching()
            return true
        }
        restore = Task { [weak self] in
            try? await Task.sleep(for: hold)
            guard !Task.isCancelled else { return }
            self?.restoreIfUntouched()
        }
        startWatching(bundleID)
        return true
    }

    /// Both triggers end in `restoreIfUntouched`, so the guard against
    /// overwriting a newer copy applies to either of them.
    ///
    /// **The sheet’s application may already be in front**, and usually is:
    /// the overlay is a non-activating panel, so ⌥Space over a browser leaves
    /// that browser frontmost, and opening a tab in an application that is
    /// already frontmost posts no activation at all. Started at `false`, the
    /// browser would never be marked as visited, every later switch would read
    /// as `.irrelevant`, and leaving would never hand the clipboard back — in
    /// precisely the commonest way of booking. So the flag is seeded from who
    /// is in front right now, not assumed.
    private func startWatching(_ bundleID: String?) {
        sheetApp = bundleID
        sawSheetApp = bundleID != nil && frontmostBundleID() == bundleID
        guard bundleID != nil, watch == nil else { return }
        watch = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] note in
            // The identifier is taken out here, in the non-isolated closure:
            // a `Notification` is not `Sendable` and cannot cross into the
            // actor, while a `String?` can.
            let bundleID = (note.userInfo?[NSWorkspace.applicationUserInfoKey]
                as? NSRunningApplication)?.bundleIdentifier
            MainActor.assumeIsolated {
                self?.noteActivation(of: bundleID)
            }
        }
    }

    /// The state machine behind the notification, reachable without one so a
    /// test can drive the whole path — seeding, transition and restore — and
    /// not merely the decision in isolation.
    func noteActivation(of bundleID: String?) {
        switch Self.activation(of: bundleID, sheetApp: sheetApp, sawSheetApp: sawSheetApp) {
        case .arrivedAtSheet:
            sawSheetApp = true
        case .leftTheSheet:
            restoreIfUntouched()
        case .irrelevant:
            break
        }
    }

    private func stopWatching() {
        if let watch {
            NSWorkspace.shared.notificationCenter.removeObserver(watch)
        }
        watch = nil
        sheetApp = nil
        sawSheetApp = false
    }

    /// Puts the snapshot back — unless somebody copied after us, in which case
    /// their copy is newer than ours and stays.
    ///
    /// An **empty** snapshot is not “nothing to do”: it is a clipboard that was
    /// empty to begin with — a fresh login where nobody has copied anything yet
    /// — and putting it back means clearing. Conflating the two would leave the
    /// name on the clipboard for good, with a limited hold chosen in settings.
    /// Whether anything was pending is `stamp`; what to put back is `saved`.
    func restoreIfUntouched() {
        let previous = saved
        let mine = stamp
        saved = nil
        stamp = nil
        restore = nil
        stopWatching()

        guard let mine, mine == pasteboard.changeCount, let previous else { return }
        pasteboard.clearContents()
        guard !previous.isEmpty else { return }
        pasteboard.writeObjects(previous)
    }

    /// A timed restoration should not be lost merely because the app quits.
    /// The explicit “leave it until something else is copied” mode has no task
    /// and is intentionally left alone.
    func restoreBeforeTermination() {
        guard restore != nil else { return }
        restoreIfUntouched()
    }

    /// Items taken off a pasteboard are void once it is cleared, so each one is
    /// copied by its readable types.
    ///
    /// `nil` — **all of it or none of it**, and a single type that declines to
    /// hand over its data makes it none.
    ///
    /// One item carries the same content in several representations: a copied
    /// paragraph arrives as `public.html` and `public.utf8-plain-text` at once,
    /// and some of them are promises rather than data — a file promise, or a
    /// provider whose app has since quit. Keeping the readable ones and
    /// dropping the rest is tempting and wrong: which representation the next
    /// application asks for is its business, not ours, and an item handed back
    /// without the one it wanted is not the thing the person copied. Since we
    /// cannot tell which that is, we do not get to choose — either the
    /// clipboard can be put back exactly, or we leave it alone.
    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem]? {
        var result: [NSPasteboardItem] = []
        for source in pasteboard.pasteboardItems ?? [] {
            let copy = NSPasteboardItem()
            for type in source.types {
                guard let data = source.data(forType: type) else { return nil }
                copy.setData(data, forType: type)
            }
            result.append(copy)
        }
        return result
    }
}
